version: '2'
services:
  db:
    image: postgres:11.8-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - roasted_data:/var/lib/postgresql/data

  web:
    build: .
    entrypoint: ["/app/lib/docker-entrypoint.sh"]
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DB_USERNAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  roasted_data: