version: '2'
services:
  db:
    image: postgres:11.8-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
      DB_USERNAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - db
